Desarrollo-A/sisfusion

- dist/js/controllers/postventa/solicitudes_escrituracion.js
> prueba de vscode

- application/controllers/Comisiones.php
- application/models/Comisiones_model.php
- application/views/ventas/comisiones_colaborador.php
CAMBIOS URIEL MODAL PARA CAPTURA DE CP
> Modal para capturar el codigo postal

- dist/js/controllers/comisiones/panel_prestamos.js
y cambio de colores por clases
> datatable correcciones

- application/controllers/Comisiones.php
- application/models/Comisiones_model.php
> archivos completos p2

- application/controllers/Api.php
- application/models/Internomex_model.php
- application/models/Registrolote_modelo.php
Api.php: se incluye servicio para la consulta de información de ventas para internomex
Internomex_model.php: se modifica la consulta para la obtención de la información de ventas
Registrolote_modelo: se modifica consulta getdp_DS
> Cambios generales

- application/controllers/Api.php
- application/controllers/Contraloria.php
- application/controllers/Documentacion.php
- application/models/Contraloria_model.php
- application/models/Documentacion_model.php
- application/models/Internomex_model.php
- application/models/Reporte_model.php
- application/models/VentasAsistentes_model.php
- application/views/contraloria/inventarioComisionistas_view.php
- dist/js/controllers/contraloria/inventarioComisionistas.js
Se agregan funciones eliminadas sin validar en controlador y modelo de documentación.
Se agrega vista de inventario por comisionista
> Ajustes generales

- application/models/Reestructura_model.php
Cambios en la querie de getReporteEstatus. Los datos ya no vienen repetidos en el mismo registro.
> Cambio: datos no repetidos en getReporteEstatus

- application/controllers/Reestructura.php
En el reporte de cancelaciones para la vista de Alex se le modifico la consulta porque no filtraba bien, se le agregó el filtro en la otra consulta del UNION.
> Arreglo de filtro querie

- application/controllers/Reestructura.php
Validación de aquellos lotes que contengan una línea de venta que no coincida con su plan de comisión.
> Validación de linea de venta no coincida con plan comisión

- application/controllers/Reestructura.php
- application/models/Reestructura_model.php
- application/views/template/footer.php
- dist/js/controllers/reestructura/cancelacion.js
Filtro para sus asistentes de alex
> Filtro para sus asistentes de alex

- application/controllers/Reestructura.php
- application/views/reestructura/cancelacion_view.php
- dist/js/controllers/reestructura/cancelacion.js
Agrega idstatuslote 17 en filtro
> Agrega idstatuslote 17 en filtro

- application/views/contratacion/datos_status8Contratacion_asistentes_view.php
- dist/js/controllers/contratacion/vista_8_contratacion.js
- dist/js/controllers/documentacion/documentacion.js
Se cambio la manera de subir, modificar y cambiar archivos de complementos de pagos para el estatus 8 de contratación.
> Proceso subida de archivos modificado para complemento de pagos

- application/controllers/Reestructura.php
Se retiró a los usuarios del preproceso de reestructura en juridico:
-- JOSE DANIEL MORALES RESENSIZ (2762)
-- CARLOS ANDRES MORALES RESENDIZ (2747)
Quedando los usuarios:
-- Jennifer Areli Lopez Garcia. (2876)
-- Karina Angelica Gonzáles De la O. (10463)
-- Luis Octavio Vera Velázquez. (2765)
-- Cecilia Judith Piña Enríquez. (13691)
> Usuarios retirados de preproceso Juridico por ticket #83181

- application/models/Contraloria_model.php
- application/models/Contratacion_model.php
- application/models/Registrolote_modelo.php
- application/models/Reporte_model.php
- application/views/contraloria/vista_9_contraloria.php
- application/views/contratacion/datos_lote_contratacion_view.php
- application/views/contratacion/datos_lotesContratados_view.php
- application/views/reportes/reporteTrimestral.php
- dist/js/controllers/contraloria/reportesTrimestrales.js
- dist/js/controllers/contraloria/vista_9_contraloria.js
- dist/js/controllers/contratacion/datos_lote_contratacion.js
- dist/js/controllers/contratacion/datos_lotesContratados.js
Columna de PORCENTAJE ENGANCHE agregada a reportes que pidió Mariela.
REPORTES:
1.- CONSULTA TRIMESTRAL
2.- LOTES CONTRATADOS
3.- ESTATUS 9
4.- INVENTARIO
> Columna de PORCENTAJE ENGANCHE agregada a reportes

- application/controllers/Contraloria.php
- application/models/Contraloria_model.php
- application/views/contraloria/status9Report.php
- application/views/contraloria/vista_5_contraloria.php
- application/views/contratacion/datos_lote_contratacion_view.php
- dist/js/controllers/contraloria/status9Report.js
- dist/js/controllers/contraloria/vista_5_contraloria.js
- dist/js/controllers/contratacion/datos_lote_contratacion.js
- dist/js/controllers/contratacion/vista_8_contratacion.js
Columna de porcentaje enganche en reportes y modif de revision.
> Columna de porcentaje enganche en reportes y modif de revision. 

- application/controllers/Casas.php
- application/models/CasasModel.php
- dist/js/components/forms.js
- dist/js/controllers/casas/cartera.js
- dist/js/controllers/general/main_services.js
Formulario para crear un cliente, y poder editar temporalmente
> Alta clientes pre proceso casas

- application/controllers/Casas.php
- application/models/CasasModel.php
- dist/js/controllers/casas/cartera.js
Se agregan campos para la creación de los clientes al momento de crear clientes en pre proceso de casas.
> Se agregan campos para la creación de los clientes en pre proceso.

- application/controllers/BaseController.php
- application/controllers/ComisionesNeo.php
- application/controllers/Postventa.php
- application/controllers/Reestructura.php
- application/models/CasasModel.php
- application/models/ComisionesNeo_model.php
- application/models/Postventa_model.php
- application/views/casas/creditoBanco/ingresar_adeudos.php
- application/views/postventa/asignar_escrituracion_view.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
- dist/js/controllers/postventa/asignar_escrituracion.js
Se creó un módulo para agregar la marca de titulación. Poder cargar formas de pago en caso de no contar con la marca de escrituración, en caso contrario no requerirlo.
> Modulo para agregar marca de titulación, cargar formas de pago

- application/controllers/Casas.php
- application/models/CasasModel.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
- dist/js/controllers/casas/creditoBanco/orden_compra_firma.js
- dist/js/controllers/general/main_services.js
- dist/js/funciones-generales.js
Fixes primera prueba completa casas
> Pruebas completas Casas

- application/controllers/Casas.php
- application/models/CasasModel.php
- application/views/casas/asignacion_esquema.php
- dist/js/controllers/casas/asignacion_esquema.js
- dist/js/controllers/casas/cartera.js
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
PR para solucionar las incidencias encontradas.
> Incidencias fixes

- application/controllers/Casas.php
- application/models/CasasModel.php
- application/views/casas/creditoDirecto/documentacion.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
- dist/js/controllers/casas/creditoDirecto/documentacion.js
Soluciones a algunas incidencias
> Incidencias

- application/controllers/Casas.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
> Pruebas casas

- application/controllers/Casas.php
Fix paso 4, validación faltante
> Fix paso 4

- application/controllers/Casas.php
- application/views/casas/creditoBanco/orden_compra_view.php
- dist/js/controllers/casas/creditoBanco/orden_compra_firma.js
- dist/js/controllers/casas/creditoBanco/propuesta_firma.js
Soluciones a algunas incidencias reportadas
> Fixes incidencias

- dist/js/controllers/casas/creditoBanco/documentacion.js
Se cambia el tipo de archivo (formas de pago) paso 2
> Paso 2 excel formas de pago

- application/models/CasasModel.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
Solución al estatus de la etiqueta en el paso 2 de casas. Estatus escrituración
> Fix modulo escrituración

- application/controllers/Casas.php
- application/models/CasasModel.php
- application/views/casas/creditoDirecto/cajas_adeudo_view.php
- application/views/template/modals.php
- dist/js/components/forms.js
- dist/js/controllers/casas/creditoBanco/documentacion.js
- dist/js/controllers/casas/creditoBanco/orden_compra_firma.js
- dist/js/controllers/casas/creditoBanco/propuesta_firma.js
- dist/js/controllers/casas/creditoBanco/tipo_proveedor.js
Se agregan incidencias pendientes
> Incidencias pendientes

- application/controllers/Casas.php
- application/models/CasasModel.php
- dist/js/components/forms.js
- dist/js/controllers/casas/creditoBanco/reporte_casas_venta.js
- dist/js/controllers/casas/reporte_casas.js
> Fix Timeline

- application/controllers/Pagoscasas.php
- application/models/CasasModel.php
- application/models/PagosCasasModel.php
- application/views/pagos_casas/carga_complemento_dos.php
- application/views/pagos_casas/confirmar_pago_dos.php
- application/views/pagos_casas/validar_pago_dos.php
- dist/js/controllers/pagos_casas/carga_complemento_dos.js
- dist/js/controllers/pagos_casas/confirmar_pago_dos.js
- dist/js/controllers/pagos_casas/iniciar_proceso.js
- dist/js/controllers/pagos_casas/validar_pago_dos.js
Se agregan cambios para repetir el proceso del 7 al 11 hasta finalizar
> Cambios pago casas

- application/controllers/Casas.php
- application/controllers/Postventa.php
- application/models/CasasModel.php
- application/models/Postventa_model.php
- dist/js/components/forms.js
- dist/js/controllers/casas/creditoBanco/carta_auth.js
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
- dist/js/controllers/casas/creditoBanco/propuesta_firma.js
- dist/js/controllers/postventa/asignar_escrituracion.js
Se agregan valdiaciones para agregar la marca de titulación. Al igual que la creación del documento de formas de pago
> Marca Escrituración

- application/controllers/Casas.php
- application/models/Postventa_model.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
Correcion revisionEscrituración
> Correcion revisionEscrituración

- application/controllers/Pagoscasas.php
- dist/js/controllers/pagos_casas/confirmar_pago_dos.js
- dist/js/controllers/pagos_casas/solicitar_avance.js
- dist/js/controllers/pagos_casas/validar_pago_dos.js
Se arregla el paso 7 para poder visualizar los documentos correctamente en el flujo de pagos en casas
> Paso 7 errores

- application/controllers/Postventa.php
- application/models/Postventa_model.php
- dist/js/controllers/postventa/asignar_escrituracion.js
Dato faltante en js para agregar null
> Dato faltante

- application/controllers/Postventa.php
- application/models/Postventa_model.php
- dist/js/controllers/casas/creditoBanco/ingresar_adeudos.js
- dist/js/controllers/postventa/asignar_escrituracion.js
Se agregan cambios para el módulo de escrituración (crear,editar,asignar) un cliente. Se agregan validaciones para el vobo de escrituración para el paso 2
> Cambios módulo escrituración

- application/controllers/Casas.php
Se agrega la creación del documento faltante
> Error documento

- dist/js/controllers/dashboard/inicio/dashboardHome.js
- dist/js/jquery.i18n/langs.json
- dist/js/jquery.i18n/load.js
> Dashboard Home fixes

- application/models/VentasAsistentes_model.php
qry de getLegalRejections restaurada
> qry de getLegalRejections restaurada

- dist/js/controllers/contratacion/vista_8_contratacion.js
Replace a una función debido al nombre del cliente
> Replace a una función debido al nombre del cliente

- dist/js/controllers/documentacion/documentacion.js
Bug cerrar modal documentación
> Bug cerrar modal documentación
